---
title: "COVID 19 Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(mapproj)
library(maps)
library(sf)
library(mapview)
library(tmap)
library(spData)
library(htmltools)
library(leaflet)
library(tidyverse)

## Reading Data
confirmed_cases <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
deaths <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")
recoveries <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")

## HELPER FUNCTIONS ####
## Helper Function: Format dataset
format_df <- function(df){
  df <- df %>% 
    gather(date_key, date_val, -Lat, -Long, - `Country/Region`, -`Province/State`) %>%
    mutate(date_key = as.Date(date_key, "%m/%d/%y"))
  
  return(df)
}

## Helper Function: Sum by Country
country_current_total <- function(df){
  df <- df %>%
    group_by(`Country/Region`, date_key) %>% 
    summarise(date_val = sum(date_val)) %>%
    ungroup()
  
  return(df)
}

## Helper Function: Latest Total
latest_total <- function(df){
  df <- df %>%
    country_current_total() %>%
    filter(date_key == max(.$date_key)) %>%
    select(-date_key) %>%
    rename(Total = date_val) %>%
    arrange(desc(Total))
  
  return(df)
}


## DATA PREP ####
## Clean DFs
confirmed_cases <- confirmed_cases %>% format_df()
deaths <- deaths %>% format_df()
recoveries <- recoveries %>% format_df()

### World Map ####
#partly from https://stackoverflow.com/questions/30706124/plotting-the-world-map-in-r
WorldData <- map_data('world') %>% filter(region != "Antarctica") %>% fortify 

# Adding Column Flag for Countries w Confirmed Cases
countries_w_confirmed_cases <- confirmed_cases %>% 
  filter(date_val > 0) %>% 
  distinct(`Country/Region`) %>%
  mutate(`Country/Region` = case_when(
    `Country/Region` == "US" ~ "USA",
    `Country/Region` == "Mainland China" ~ "China",
    T ~ `Country/Region`
  ))

WorldData <- WorldData %>% 
  mutate(infected = region %in% countries_w_confirmed_cases$`Country/Region`)
```


Row {data-height=650}
-------------------------------------
    
### COVID-19 Geographic Spread {.no-padding}
    
```{r World Map Plot, fig.width=20, fig.height=10}
confirmed_cases %>%
  rename(Cases = date_val) %>%
  inner_join(rename(deaths, Deaths = date_val)) %>%
  inner_join(rename(recoveries, Recoveries = date_val)) %>%
  filter(date_key == max(.$date_key)) %>%
  mutate(map_label = if_else(is.na(`Province/State`), `Country/Region`, `Province/State`)) %>%
  mutate(map_label_cases = paste(map_label, "\n Confirmed Cases:", Cases),
         map_label_deaths = paste(map_label, "\n Deaths:", Deaths),
         map_label_recoveries = paste(map_label, "\n Recoveries:", Recoveries)) %>%
  leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>%
  addCircleMarkers(weight = 1,
                   color = "red",
                  label = ~as.character(map_label_cases),
                   radius = ~ log10(Cases) * 1.5, 
                   popup = ~htmlEscape(map_label),
                   stroke = FALSE,
                  fillOpacity = 0.5,
                  labelOptions = labelOptions(textsize = "15px"),
                  group = "Confirmed Cases") %>%
  addCircleMarkers(weight = 1,
                   color = "black",
                   label = ~as.character(map_label_deaths),
                   radius = ~ log10(Deaths) * 1.5, 
                   popup = ~htmlEscape(map_label_deaths),
                   stroke = FALSE,
                   fillOpacity = 0.5,
                   labelOptions = labelOptions(textsize = "15px"),
                   group = "Deaths") %>%
  addCircleMarkers(weight = 1,
                   color = "green",
                   label = ~as.character(map_label_recoveries),
                   radius = ~ log10(Recoveries) * 1.5, 
                   popup = ~htmlEscape(map_label_recoveries),
                   stroke = FALSE,
                   fillOpacity = 0.5,
                   labelOptions = labelOptions(textsize = "15px"),
                   group = "Recoveries") %>%
  addLayersControl(
    overlayGroups = c("Confirmed Cases", "Deaths", "Recoveries"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>% hideGroup("Deaths") %>% hideGroup("Recoveries")
```
   
Row {data-height=550}
-------------------------------------
    
### Progress Since 100th Case {.no-padding}
    
```{r Progress since 100th Case}
confirmed_cases_by_country <- confirmed_cases %>% country_current_total()

most_cases_country <- confirmed_cases_by_country %>% 
  filter(date_key == max(.$date_key) & `Country/Region` != "Others") %>% 
  arrange(desc(date_val)) %>% 
  top_n(4, date_val)

confirmed_cases_spread <- confirmed_cases_by_country %>% 
  filter(date_val > 100) %>%
  split(.$`Country/Region`) %>%
  purrr::map(function(x) mutate(x, x_axis = c(1:nrow(x))))

confirmed_cases_spread <- do.call("rbind.data.frame", confirmed_cases_spread)

color_scheme <- c("#003399","#FF2B4F", "#fcab27", "darkgrey", "#3686d3", "#C76EA9")

confirmed_cases_spread %>%
  mutate(country_label = case_when(
    `Country/Region` %in% most_cases_country$`Country/Region` ~ `Country/Region`,
    T ~ "Other"
  )) %>%
  ggplot(aes(x_axis, date_val, group = `Country/Region`,  color = `country_label`)) +
  geom_line(data = . %>% filter(`Country/Region` %in% most_cases_country$`Country/Region`), size = 1) +
  geom_line(data = . %>% filter(!`Country/Region` %in% most_cases_country$`Country/Region`), alpha = 0.25) + #plots all other countries
  geom_point(data = . %>% filter(date_key == max(date_key) & country_label != "Other")) +
  scale_x_continuous(breaks = seq(0, 80, 7)) +
  scale_y_continuous(breaks = c(1, 100, 1000, 10000, 100000), 
                     labels = c(1, 100, 1000, 10000, "100000"), #avoid R's exponential notation
                     trans = "log") +
  scale_color_manual(values = color_scheme) + 
  labs(x = "Days since 100th Recorded Case", y = "# Confirmed Cases", color = "Country")
```
    
### Current Tally {.no-padding}

```{r Current Tally}
total_confirmed_cases <- confirmed_cases %>% latest_total()  %>% rename(`Total Cases` = Total)
total_deaths <- deaths %>% latest_total() %>% rename(`Total Deaths` = Total)
total_recoveries <- recoveries  %>% latest_total() %>% rename(`Total Recoveries` = Total)

col_scale <- c("Total Recoveries"= "#00429d", "Ongoing Cases" =  "grey", 
               #"Total Recoveries" = "#73a2c6",  
               "Total Deaths" = "#93003a"
               #"Total Recoveries" = "#00429d"
               )

total_confirmed_cases %>% 
  inner_join(total_deaths) %>% 
  inner_join(total_recoveries) %>%
  mutate(`Ongoing Cases` = `Total Cases` - `Total Deaths` - `Total Recoveries`) %>% #so it displays properly
  select(- `Total Cases`) %>%
  gather(val_key, val_val, - `Country/Region`) %>%
  filter(`Country/Region` %in% most_cases_country$`Country/Region`) %>%
  ggplot(aes(fct_reorder(`Country/Region`, val_val), val_val, fill = val_key)) +
  geom_col() +
  scale_y_continuous(breaks=seq(0, 200000, 20000)) +
  scale_fill_manual(values = col_scale) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "", y = "", fill = "") 
```